# Generated by Django 4.1.7 on 2023-02-24 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_alter_article_options_alter_article_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=64, verbose_name='Текст комментария')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_articles', to='service.article', verbose_name='Статья')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='article',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='author',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
